# Generated by Django 3.1.2 on 2021-01-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='licence_plate',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
