version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/src/static
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - static_volume:/src/static

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend


volumes:
  static_volume: