version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - app

  app:
    container_name: app
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/static
    command: bash -c "ls && python manage.py migrate && python manage.py collectstatic --no-input --clear &&
      gunicorn config.asgi:application --workers 4 --bind :8000 --reload --timeout 90 -k uvicorn.workers.UvicornWorker"

volumes:
  static_volume: