version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/static
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/backend/static
    command: bash -c "ls && python manage.py migrate && python manage.py collectstatic --no-input --clear &&
      gunicorn config.wsgi:application --workers 4 --bind :8000 --reload --timeout 90"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    command: yarn serve
    ports:
      - 8080:8080
    depends_on:
      - backend


volumes:
  static_volume: