# Generated by Django 3.1.2 on 2021-01-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
